% regular_testing_ms('Board');
% regular_testing_ms('Candela_m1.10');
% regular_testing_ms('CAVIAR1');
% regular_testing_ms('CAVIAR2');
% regular_testing_ms('CaVignal');
regular_testing_ms('Foliage');
% regular_testing_ms('HallAndMonitor');
% regular_testing_ms('HighwayI');
% regular_testing_ms('HighwayII');
% regular_testing_ms('HumanBody2');
% regular_testing_ms('IBMtest2');
% regular_testing_ms('PeopleAndFoliage');
% regular_testing_ms('Snellen');
% regular_testing_ms('Toscana');
