function lab = drfiGetSegmentSaliencyLabel( gtmask, imsegs )
    % gtmask    ground truth of the PIXEL_WISE annotation
    % imdata    generated by the getImData
    % splabel   the label of the superpixels, coming from multi segmentation
    % segment   segment = unique(splabel)
    % lab       {-1, 0, 1} -1 is background, 1 is the salient object, and 0 is uncertain
    thresh = 0.75;
    
    gtmask(gtmask >= 128) = 255;
    gtmask(gtmask < 128) = 0;
    gtmask = double(gtmask);
    
    spstats = regionprops( imsegs.segimage, 'PixelIdxList' );
    
    nseg = imsegs.nseg;
    
    lab = zeros( nseg, 1 );
    
    for ix = 1 : nseg
        pixels = spstats(ix).PixelIdxList;
        [saliency occurence] = mode( gtmask(pixels) );
        if occurence / max(length(pixels), eps) < thresh
            lab(ix) = 0;
        else
            if saliency == 255
                lab(ix) = 1;
            elseif saliency == 0
                lab(ix) = -1;
            else
                error( 'error in gtmask' );
            end
        end
    end
end